# Generated by Django 5.1.1 on 2024-11-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_height_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
