# Generated by Django 5.1.1 on 2024-11-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_username_alter_user_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, default='0000000000', max_length=10, null=True, unique=True),
        ),
    ]
