# Generated by Django 5.1.1 on 2024-11-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('Sun', 'ראשון'), ('Mon', 'שני'), ('Tue', 'שלישי'), ('Wed', 'רביעי'), ('Thu', 'חמישי'), ('Fri', 'שישי'), ('Sat', 'שבת')], default='Sun', max_length=3, null=True),
        ),
    ]
