# Generated by Django 5.1.1 on 2024-11-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_day_of_week'),
        ('workouts', '0004_alter_workout_options_workout_calories_burned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='workouts',
            field=models.ManyToManyField(blank=True, related_name='users', to='workouts.workout'),
        ),
    ]
