# Generated by Django 5.1.1 on 2024-11-10 05:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workout_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='workout',
            name='calories_burned',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='workout_date',
        ),
        migrations.AddField(
            model_name='workout',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
